language: python
python:
  - 2.5
  - 2.6
  - 2.7

install: pip install --upgrade 'nose>=1.2.1' tvdb_api && ( [ $TRAVIS_PYTHON_VERSION == "2.5" ] && pip install simplejson || echo -n)

script: nosetests
