language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

script: python setup.py test

# Use container-based infrastructure, for no specific reason.
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
